channels:
  - conda-forge
  - defaults
dependencies:
  - inferno=v0.4.0
  - pip
  - python=3.7.0
  - pytorch
  - torchvision
  - pip:
    - sphinx==2.2.0
    - sphinx-gallery==0.4.0
    - sphinx-rtd-theme==0.4.3

